# Generated by Django 4.0 on 2022-11-24 13:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.URLField(blank=True, max_length=256, validators=[django.core.validators.RegexValidator('^(https://api\\.bitpack\\.app/asset/houston\\-dev/image/)(.+$)')], verbose_name='Image'),
        ),
    ]
