# Generated by Django 4.0 on 2022-12-02 19:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_comment_parent'),
        ('access', '0004_user_liked_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followed_users',
            field=models.ManyToManyField(blank=True, related_name='user_followed_users', through='connect.Like', to=settings.AUTH_USER_MODEL, verbose_name='liked posts'),
        ),
        migrations.AlterField(
            model_name='user',
            name='liked_posts',
            field=models.ManyToManyField(blank=True, related_name='user_liked_posts', through='connect.Like', to='content.Post', verbose_name='liked posts'),
        ),
    ]
