# Generated by Django 4.0 on 2022-12-05 15:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0005_user_followed_users_alter_user_liked_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followed_users',
            field=models.ManyToManyField(blank=True, related_name='user_followed_users', through='connect.Follow', to=settings.AUTH_USER_MODEL, verbose_name='followed users'),
        ),
    ]
