# Generated by Django 4.0 on 2022-12-05 17:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0006_alter_user_followed_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followed_users',
        ),
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='user_followers', through='connect.Follow', to=settings.AUTH_USER_MODEL, verbose_name='followed by users'),
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='user_following', through='connect.Follow', to=settings.AUTH_USER_MODEL, verbose_name='followed users'),
        ),
    ]
