# Generated by Django 4.0 on 2022-11-24 14:08

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Published'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_unlisted',
            field=models.BooleanField(default=False, verbose_name='Unlisted'),
        ),
        migrations.AlterField(
            model_name='post',
            name='assets',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=256, validators=[django.core.validators.RegexValidator('^(https://api\\.bitpack\\.app/asset/houston\\-dev/image/)(.+$)')]), blank=True, default=list, size=None, verbose_name='Assets'),
        ),
    ]
