# Generated by Django 4.0 on 2022-11-24 15:12

from django.db import migrations, models
import django.db.models.deletion
import project.utils.uuid
import project.validators


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_alter_user_image'),
        ('content', '0002_post_is_published_post_is_unlisted_alter_post_assets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=project.utils.uuid.get_uuid, editable=False, unique=True, verbose_name='UUID')),
                ('metadata', models.JSONField(blank=True, default=dict, null=True, validators=[project.validators.TypeValidator(dict)], verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('body', models.TextField(verbose_name='Body')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='access.user', verbose_name='Owner')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.comment', verbose_name='Parent')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.post', verbose_name='Post')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
