# Generated by Django 4.0 on 2022-12-02 16:17

from django.db import migrations, models
import django.db.models.deletion
import project.utils.uuid
import project.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0005_alter_comment_parent'),
        ('access', '0003_user_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=project.utils.uuid.get_uuid, editable=False, unique=True, verbose_name='UUID')),
                ('metadata', models.JSONField(blank=True, default=dict, null=True, validators=[project.validators.TypeValidator(dict)], verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='access.user', verbose_name='owner')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.post', verbose_name='post')),
            ],
            options={
                'verbose_name': 'post like',
                'verbose_name_plural': 'post likes',
                'ordering': ['-created_at'],
                'unique_together': {('post', 'owner')},
            },
        ),
    ]
